Verify signatures of downloaded Kubernetes artifacts and bump versions
gardener/hyperkube pull request #15
Opened 2024-02-12 13:44 UTC by dnaeon

**What this PR does / why we need it**:

This PR adds support for verifying the signatures of Kubernetes artifacts. 

It also:

- Bumps the `KUBERNETES_VERSION` to `v1.29.1`
- Bumps the `MINIMUM_KUBERNETES_VERSION` to `v1.27.0` (`v1.26.x` will be EOL'd at 28-02-2024, so `v1.27.x` will be the last supported release in about ~ 2 weeks)

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-02-12 15:33 UTC, vpnachev reviewed
/reviewed ok-to-test

2024-02-12 16:49 UTC, vpnachev commented
/invite @gardener/gardener-maintainers

2024-03-01 09:32 UTC, dnaeon commented
PR rebased.

2024-03-05 08:06 UTC, vpnachev requested changes

2024-03-05 09:22 UTC, dnaeon commented on scripts/get-k8s-binary.sh
> +        exit 64
The exit code is based on [sysexits.h(3)](https://manpages.debian.org/bookworm/manpages-dev/sysexits.h.3head.en.html), where `EX_USAGE (64)` specifies a command-line usage error.

2024-03-05 09:31 UTC, merged