Add a Makefile
gardener/hyperkube pull request #3
Opened 2020-10-25 11:50 UTC by berendt

2020-10-26 07:06 UTC, rfranzke requested changes

2020-10-26 07:06 UTC, rfranzke commented on Makefile
> +# Copyright (c) 2017 SAP SE or an SAP affiliate company. All rights reserved.
```suggestion
# Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved.
```

2020-10-26 07:06 UTC, rfranzke commented on VERSION
> +v1.12.0-dev
What is this file used for? I guess it can be deleted

2020-10-26 08:46 UTC, berendt commented on VERSION
> +v1.12.0-dev
For the default tag of the image.

``IMAGE_TAG          := $(shell cat VERSION)``

2020-10-26 08:48 UTC, rfranzke commented on VERSION
> +v1.12.0-dev
Hm, but why do we need it? The tag should always be the KUBERNETES_VERSION that is being used, or?

2020-10-26 08:50 UTC, berendt commented on VERSION
> +v1.12.0-dev
The Makefile is from gardener/terraformer. There the VERSION is used as tag. KUBERNETES_VERSION makes more sense here, yes.

2020-10-26 08:52 UTC, rfranzke approved these changes
/lgtm
/invite @ialidzhikov

2020-10-28 06:53 UTC, ialidzhikov approved these changes
/lgtm

2020-10-28 06:53 UTC, merged